name: GitLeaks Scan

on:
  push:
    branches:
      - main  # Modify this to match your repository's main branch

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitLeaks
      run: |
        wget -q -O gitleaks https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

    - name: Run GitLeaks
      run: |
        gitleaks --repo=${{ github.repository }} --redact
